stages:
    - build
    - test

build-job:
    stage: build
    script:
        - echo "Building the Demo Project.."
        - echo "Compile or setup commands go here"

test-job:
    stage: test
    script:
        - echo "Running tests..."
        - echo "Pretends this runs unit tests"
